### ISSUE TITLE
Cannot refer to same property twice

### ISSUE THREAD

**Issue by larsga** [larsga/Duke#208]
The below comes from an email from Andy Dean:

I'm trying to use a single column to create multiple properties.  For example:

      <column name="zip_code"
              property="ZIP_CODE"
              cleaner="no.priv.garshol.duke.cleaners.DigitsOnlyCleaner"/>

      <column name="zip_code"
              property="THREE_DIGIT_ZIP"
              cleaner="ThreeDigitZip"/>

When I do so I get an exception, although either property definition by themselves works fine.  

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at no.priv.garshol.duke.datasources.CSVDataSource$CSVRecordIterator.<init>(CSVDataSource.java:153)
	at no.priv.garshol.duke.datasources.CSVDataSource.getRecords(CSVDataSource.java:99)
	at no.priv.garshol.duke.Processor.index(Processor.java:393)
	at no.priv.garshol.duke.Processor.link(Processor.java:316)
	at no.priv.garshol.duke.Duke.main_(Duke.java:176)
	at no.priv.garshol.duke.Duke.main(Duke.java:37)

**Comment by larsga** [comment]
Fixed in latest commit
