### ISSUE TITLE
Can not get any examples to work

### ISSUE THREAD

**Issue by AbsoluteResults** [larsga/Duke#215]
I'm very interested in this project but I cannot seem to even get out of the gate with it.

I grabbed the latest version and installed it. Added duke-core/*, duke-lucene/*,etc to CLASSPATH and I could run the executable

I then tried the LinkingCountries example. I got the raw CSV files, raw TXT file and raw XML file. When running I got an error which is fine I suppose....but someone should likely have an actual correct CSV file. I am not sure which file its having a problem with

Exception in thread "main" no.priv.garshol.duke.DukeException: Unbalanced quote in CSV file
        at no.priv.garshol.duke.utils.CSVReader.next(CSVReader.java:110)
        at no.priv.garshol.duke.datasources.CSVDataSource$CSVRecordIterator.findNextRecord(CSVDataSource.java:204)
        at no.priv.garshol.duke.datasources.CSVDataSource$CSVRecordIterator.next(CSVDataSource.java:232)
        at no.priv.garshol.duke.datasources.CSVDataSource$CSVRecordIterator.next(CSVDataSource.java:137)
        at no.priv.garshol.duke.Processor$BasicIterator.next(Processor.java:677)
        at no.priv.garshol.duke.Processor$BatchIterator.next(Processor.java:650)
        at no.priv.garshol.duke.Processor$BatchIterator.next(Processor.java:633)
        at no.priv.garshol.duke.Processor.link(Processor.java:331)
        at no.priv.garshol.duke.Duke.main_(Duke.java:175)
        at no.priv.garshol.duke.Duke.main(Duke.java:35)

I then tried the SemanticDogfood example. When running this I get errors about Lucene. I saw there was discussion about what version of Lucene to use so I tried 3.6.0, 4.0.0, and 4.8.0. For all of them I got the source and compiled with ant as per the Apache instructions, then put the lucene-core-4.8-SNAPSHOT.jar in the CLASSPATH also as Apache suggested and still all errors are either StandardAnalyzer or KeywordAnalyzer

Is there another resource to learn to set everything up? I am very interested in using this and pitching in if I can but I cannot get even the examples to work. Any help hugely appreciated.

**Comment by AbsoluteResults** [comment]
Whoops sorry realized the trace of the Lucene errors was not included

java no.priv.garshol.duke.Duke --testfile=dogfood-test.txt --testdebug --showmatches dogfood.xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/lucene/analysis/standard/StandardAnalyzer
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at no.priv.garshol.duke.ConfigLoader.instantiate(ConfigLoader.java:291)
        at no.priv.garshol.duke.ConfigLoader.access$100(ConfigLoader.java:31)
        at no.priv.garshol.duke.ConfigLoader$ConfigHandler.startElement(ConfigLoader.java:199)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1140)
        at no.priv.garshol.duke.ConfigLoader.load(ConfigLoader.java:49)
        at no.priv.garshol.duke.Duke.main_(Duke.java:64)
        at no.priv.garshol.duke.Duke.main(Duke.java:35)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.standard.StandardAnalyzer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 18 more

**Comment by tbonza** [comment]
**Similar Problem**

I couldn't get the Genetic Algorithm example to work (see [GeneticAlgorithm wiki](https://github.com/larsga/Duke/wiki/GeneticAlgorithm)). It looks like the csv files are corrupted in various ways.  I was able to start fixing the dbpedia csv file but I still haven't resolved issues with the monopedia file. 

*Does someone have csv files for the Genetic Algorithm example that are working?*

The script I used to fix `countries-dbpedia.csv` is [here](https://github.com/tbonza/data_mining/blob/master/dedupe/misc/validate.py). If there's no resolution, I can work on getting monopedia working next week.

**Comment by larsga** [comment]
> I am not sure which file its having a problem with

Good point. I fixed it now so that it reports which file it is.

**Comment by larsga** [comment]
It turns out that there was a bug in the code that detects unbalanced quotes, and the bug wasn't detected by the test suite. I've fixed the bug now and added a test case for it so that it doesn't come back. Sorry about this.

Please check again, but the problems should be solved now. If they persist, please reopen the bug.
